/*
 * ultrasonic.h
 *
 *  Created on: ???/???/????
 *      Author: Ehab Mohamed
 */

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "std_types.h"

/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/

#define ULTRASOINC_TRIG_PORT PORTB_ID
#define ULTRASOINC_TRIG_PIN  PIN5_ID

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/

/*
 * Description : Function to initialize the Ultrasonic driver
 * 	1. Initialize the ICU driver as required.
 * 	2. Setup the ICU call back function.
 * 	3. Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void);
/*
 * Description : Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void);
/*
 * Description : Function to Read the measured distance
 * 	1. Send the trigger pulse by using Ultrasonic_Trigger function.
 * 	2. Calculation (distance in cm)
 */
uint16 Ultrasonic_readDistance(void);
/*
 * Description : This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);

#endif /* ULTRASONIC_H_ */
